- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: stop the nginx
    ansible.builtin.package:
     name: nginx
     state: absent
  - name: stop the nginx
    ansible.builtin.service:
     name: nginx
     state: stopped